apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "tweets*"
    basicAuth: false
    isDefault: true
    jsonData:
      interval: "5s"
      timeField: "timestamp"
      esVersion: "8.11.0"
      includeFrozen: false
      logMessageField: "message"
      logLevelField: "level"
      maxConcurrentShardRequests: 5
    readOnly: false